{{- if and .Values.ingestKey (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-metrik
type: Opaque
stringData:
  {{ .Values.secretKey }}: {{ .Values.ingestKey | quote }}
{{- end }}
